import assert from "node:assert/strict";
import test from "node:test";
import { existsSync } from "node:fs";

const developmentPreviewMeta =
  /<meta(?=[^>]*\bname=["']codex-preview["'])(?=[^>]*\bcontent=["']development["'])[^>]*>/i;

test("renders development preview metadata", async (t) => {
  const workerUrl = new URL("../dist/server/index.js", import.meta.url);
  if (!existsSync(workerUrl)) {
    t.skip("dist/server/index.js is generated by npm run build; source-only regression skips rendered artifact validation.");
    return;
  }
  workerUrl.searchParams.set("test", `${process.pid}-${Date.now()}`);
  const { default: worker } = await import(workerUrl.href);

  const response = await worker.fetch(
    new Request("http://localhost/", {
      headers: { accept: "text/html" },
    }),
    {
      ASSETS: {
        fetch: async () => new Response("Not found", { status: 404 }),
      },
    },
    {
      waitUntil() {},
      passThroughOnException() {},
    },
  );

  assert.equal(response.status, 200);
  assert.match(
    response.headers.get("content-type") ?? "",
    /^text\/html\b/i,
  );
  assert.match(await response.text(), developmentPreviewMeta);
});

// Support-team assignment regression markers
// Expected implementation markers: /api/support-teams, tickets.assign,
// assignedTeamId, assignedUserId, reassigned.
